<?php

/**
 * @file
 * Install, uninstall, and update functions for libraries.module.
 */

/**
 * Implements hook_schema().
 */
function libraries_schema() {
  $schema['cache_libraries'] = backdrop_get_schema_unprocessed('system', 'cache');
  $schema['cache_libraries']['description'] = 'Cache table to store library information.';
  return $schema;
}

/**
 * Implements hook_update_last_removed().
 */
function libraries_update_last_removed() {
  return 7200;
}
